// See the file "COPYING" in the main distribution directory for copyright.

// An opinionated cluster-layout.zeek generator for single and multi host
// cluster deployments. The Zeek workers do not have ports allocated. For the
// multi-host use-case, expects -C /etc/zeek/cluster and will assemble a
// cluster-layout based on the files in that directory. For the single-host
// use-case, expects the individual process counts as individual arguments,
// or giving a /etc/zeek/zeek.conf file to -C.
//
// The cluster-layout.zeek content is produced on stdout or written to the
// path given to the -o flag.
//
// Usage:
//
//     zeek-cluster-layout-generator -L <loggers> -P <proxies> -W <workers>
//         -a <listen_address> -p <listen_port>
//         -m <metrics_port> -b <metrics_address>
//         [-o outfile]
//
//     zeek-cluster-layout-generator -C /etc/zeek/cluster [-o outfile]
//
//     zeek-cluster-layout-generator -C /etc/zeek/zeek.conf [-o outfile]
//
#include <unistd.h>
#include <algorithm>
#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <ostream>
#include <regex>
#include <string>
#include <vector>

#include "zeek-cluster-config.h"

namespace {

int checked_strtoul(int opt, const char* v) {
    const char* expected_end = v + std::strlen(v);
    char* end;
    auto r = std::strtoul(v, &end, 10);
    if ( end != expected_end ) {
        std::fprintf(stderr, "invalid numeric value for %c: %s\n", opt, v);
        std::exit(1);
    }

    return r;
}

/**
 * Default is a small cluster for quick testing.
 */
struct ClusterLayoutOptions {
    bool manager = true;
    int loggers = 1;
    int proxies = 1;
    std::string prefix;
    std::string workers = "1";
    int port = 27760;
    std::string address = "127.0.0.1";
    int metrics_port = 9991;
    std::string metrics_address = "127.0.0.1";

    std::string NextPort() {
        auto result = std::to_string(port) + "/tcp";
        ++port;
        return result;
    }
    std::string NextMetricsPort() {
        auto result = std::to_string(metrics_port) + "/tcp";
        // Only increment if not zero: 0/tcp means disabled!
        if ( metrics_port != 0 )
            ++metrics_port;
        return result;
    }
};

class ClusterLayout {
public:
    ClusterLayout() {
        lines.emplace_back("# Auto-generated by zeek-cluster-layout-generator");
        lines.emplace_back("");
        lines.emplace_back("redef Cluster::nodes += {");
    }

    void Done() {
        lines.emplace_back("};");
        lines.emplace_back("");
        lines.emplace_back("redef Cluster::manager_is_logger = " + std::string(total_loggers > 0 ? "F" : "T") + ";");

        lines.emplace_back("");
        lines.emplace_back("@load base/frameworks/telemetry/options");
        lines.emplace_back("");

        lines.emplace_back("# Either use ZEEK_TELEMETRY_LISTEN_ADDRESS env or the value from node$ip.");
        lines.emplace_back("const metrics_address_env = getenv(\"ZEEK_TELEMETRY_LISTEN_ADDRESS\");");
        lines.emplace_back("@if ( |metrics_address_env| > 0 )");
        lines.emplace_back("redef Telemetry::metrics_address = metrics_address_env;");
        lines.emplace_back("@else");
        lines.emplace_back("@if ( Cluster::node in Cluster::nodes )");
        lines.emplace_back("const my_ip = Cluster::nodes[Cluster::node]$ip;");
        lines.emplace_back("# Need to quote IPv6 by hand... strange...");
        lines.emplace_back("const my_ip_str = is_v4_addr(my_ip) ? cat(my_ip) : cat(\"[\", my_ip, \"]\");");
        lines.emplace_back("redef Telemetry::metrics_address = my_ip_str;");
        lines.emplace_back("@endif");
        lines.emplace_back("@endif");
        lines.emplace_back("");
        lines.emplace_back("# Always use the metrics port from the cluster layout for now");
        lines.emplace_back("# This can/may change in the future!");
        lines.emplace_back("redef Telemetry::metrics_port = Cluster::local_node_metrics_port();");
    }


    void AddNode(const std::string& name, const std::string& type, const std::string& ip,
                 const std::string& metrics_port = "", const std::string& port = "") {
        auto s = "    [\"" + name + "\"] = [$node_type=Cluster::" + type + ", $ip=" + ip;

        if ( ! port.empty() )
            s += ", $p=" + port;

        if ( name != "manager" )
            s += ", $manager=\"manager\"";

        if ( ! metrics_port.empty() )
            s += ", $metrics_port=" + metrics_port;

        s += "],";
        lines.push_back(std::move(s));

        // Slight hack for the manager_is_logger redef.
        if ( type == "LOGGER" )
            ++total_loggers;
    }

    /**
     * Workers is either just the number of workers, or a "tag1:worker1 tag2:workers2 tag3:workers3"
     * that allows to have worker-{tag}-{index} style names.
     */
    void AddWorkers(ClusterLayoutOptions& opts) {
        if ( std::ranges::all_of(opts.workers.begin(), opts.workers.end(), [](auto c) { return std::isdigit(c); }) ) {
            int workers = checked_strtoul('W', opts.workers.c_str());
            for ( int i = 1; i <= workers; i++ )
                AddNode("worker-" + std::to_string(i), "WORKER", opts.address, opts.NextMetricsPort());
        }
        else {
            // Iterate through the eth1:8,eth2:32,eth3:4 range
            // of interface tag followed by number of workers and
            // add workers for each of them.
            std::string workers_optarg = opts.workers;

            // Allow comma or space separated list.
            std::replace(workers_optarg.begin(), workers_optarg.end(), ',', ' ');

            std::cmatch cmatch;
            std::regex re_tag_workers("\\s*([-_0-9a-z]+):([0-9]+)\\s*");
            const char* p = workers_optarg.c_str();
            while ( std::regex_search(p, cmatch, re_tag_workers) ) {
                std::string tag = cmatch[1].str();
                std::string nstr = cmatch[2].str();
                int n = checked_strtoul('W', nstr.c_str());

                for ( int i = 1; i <= n; i++ )
                    AddNode("worker-" + tag + "-" + std::to_string(i), "WORKER", opts.address, opts.NextMetricsPort());

                p += cmatch.length();
            }

            if ( *p ) {
                std::fprintf(stderr, "-W invalid: '%s'\n", opts.workers.c_str());
                std::exit(1);
            }
        }
    }

    void Print(std::ostream& out) {
        for ( const auto& l : lines )
            out << l << "\n";
    }

private:
    int total_loggers = 0;
    std::vector<std::string> lines;
};

void usage(const char* prog) {
    fprintf(stdout,
            "Usage: %s -C /etc/zeek/cluster | "
            "-L <loggers> -P <proxies> -W <workers> -a <address> -p <port> "
            "-m <metrics_port> -b <metrics_address> [-o <outfile>]\n",
            prog);
}

} // namespace

int main(int argc, char* argv[]) {
    ClusterLayoutOptions opts;

    std::string config_or_cluster = "";
    std::string out = "-";
    opterr = 0;

    while ( int c = getopt(argc, argv, "hC:L:P:W:a:p:m:b:o:") ) {
        if ( c < 0 )
            break;

        switch ( c ) {
            case 'C': config_or_cluster = optarg; break;
            case 'L': opts.loggers = checked_strtoul(c, optarg); break;
            case 'P': opts.proxies = checked_strtoul(c, optarg); break;
            case 'W': opts.workers = optarg; break;
            case 'a': opts.address = optarg; break;
            case 'p': opts.port = checked_strtoul(c, optarg); break;
            case 'm': opts.metrics_port = checked_strtoul(c, optarg); break;
            case 'b': opts.metrics_address = optarg; break;
            case 'o': out = optarg; break;
            case 'h': usage(argv[0]); std::exit(0);
            case '?': std::fprintf(stderr, "unrecognized flag %c\n", optopt); std::exit(1);
        }
    }

    ClusterLayout layout;

    if ( config_or_cluster.empty() ) {
        // Include all nodes in the given ClusterLayoutOptions.
        layout.AddNode("manager", "MANAGER", opts.address, opts.NextMetricsPort(), opts.NextPort());

        for ( int i = 1; i <= opts.loggers; i++ ) {
            layout.AddNode("logger-" + std::to_string(i), "LOGGER", opts.address, opts.NextMetricsPort(),
                           opts.NextPort());
        }

        for ( int i = 1; i <= opts.proxies; i++ )
            layout.AddNode("proxy-" + std::to_string(i), "PROXY", opts.address, opts.NextMetricsPort(),
                           opts.NextPort());

        layout.AddWorkers(opts);
    }
    else {
        std::vector<std::filesystem::path> fnames;

        if ( std::filesystem::is_directory(config_or_cluster) ) {
            // If the -C argument is a directory, parse all configuration files from it
            // and assemble a cluster layout. Configs need to strictly match <hostname>.zeek.conf
            // within the directory.
            //
            // We could validate a few things here, like IP address an name conflicts,
            // but for now this should do, and technically overlapping IPs are okay
            // if the ports differ, so there's that. But IP/port overlap among processes
            // would be problematic.
            //
            // The directory must end with cluster/ as some of the configuration
            // parsing behaves differently (specifically node prefixing).
            std::regex re_conf("[a-z0-9][-a-z0-9_]*\\.zeek\\.conf$");

            auto dir = std::filesystem::path(config_or_cluster);
            if ( dir.filename().empty() ) // strip trailing slash
                dir = dir.parent_path();

            if ( dir.filename() != "cluster" ) {
                std::fprintf(stderr, "directory given to -C must end in cluster/\n");
                std::exit(1);
            }


            for ( const auto& fname : std::filesystem::directory_iterator(config_or_cluster) ) {
                if ( std::regex_match(fname.path().filename().string(), re_conf) )
                    fnames.emplace_back(fname);
            }
        }
        else if ( std::filesystem::is_regular_file(config_or_cluster) ) {
            // If it's just a file, do the same.
            fnames.emplace_back(config_or_cluster);
        }
        else {
            std::fprintf(stderr, "neither file nor directory: %s\n", config_or_cluster.c_str());
            std::exit(1);
        }

        std::sort(fnames.begin(), fnames.end());

        for ( const auto& fname : fnames ) {
            const auto absfname = std::filesystem::absolute(fname);
            auto config = zeek::detail::parse_config("/dev/null", absfname);

            // Failed to load the config file? Strange. Just exit.
            if ( ! config.Exists() || ! config.IsValid() ) {
                std::fprintf(stderr, "invalid config %s\n", absfname.string().c_str());
                for ( const auto& err : config.Errors() )
                    std::fprintf(stderr, "%s\n", err.c_str());

                std::exit(1);
            }

            int port = config.ClusterPort();
            auto next_port = [&port]() { return std::to_string(port++) + "/tcp"; };

            int metrics_port = config.MetricsPort();
            auto next_metrics_port = [&metrics_port]() {
                auto port_str = std::to_string(metrics_port) + "/tcp";
                if ( metrics_port != 0 )
                    metrics_port++;
                return port_str;
            };

            // The manager in a cluster is always named manager, no prefix here.
            if ( config.Manager() )
                layout.AddNode("manager", "MANAGER", config.ClusterAddress(), next_metrics_port(), next_port());

            for ( int i = 1; i <= config.Loggers(); i++ ) {
                layout.AddNode(config.PrefixedClusterNode("logger-" + std::to_string(i)), "LOGGER",
                               config.ClusterAddress(), next_metrics_port(), next_port());
            }

            for ( int i = 1; i <= config.Proxies(); i++ )
                layout.AddNode(config.PrefixedClusterNode("proxy-" + std::to_string(i)), "PROXY",
                               config.ClusterAddress(), next_metrics_port(), next_port());

            // Go through all interface configurations and add the required workers.
            for ( const auto& iwc : config.InterfaceWorkerConfigs() ) {
                for ( int i = 1; i <= iwc.Workers(); i++ ) {
                    layout.AddNode(config.PrefixedClusterNode(iwc.FullWorkerName(i)), "WORKER", config.ClusterAddress(),
                                   next_metrics_port());
                }
            }
        }
    }

    layout.Done();

    // stdout print?
    if ( out == "-" ) {
        layout.Print(std::cout);
        return 0;
    }

    std::ofstream os(out, std::ios::trunc);
    if ( ! os.is_open() ) {
        std::fprintf(stderr, "failed to open %s: %s\n", out.c_str(), std::strerror(errno));
        std::exit(1);
    }

    layout.Print(os);
    return 0;
} // namespace
